-- 
-- TABLE: DIAGNOSTICO 
--

CREATE TABLE DIAGNOSTICO(
    DIAGNOSTICO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE             VARCHAR2(20)     NOT NULL,
    NOMBRE            VARCHAR2(500)    NOT NULL,
    CONSTRAINT DIAGNOSTICO_PK PRIMARY KEY (DIAGNOSTICO_ID)
)
;



-- 
-- TABLE: ESPECIALIDAD 
--

CREATE TABLE ESPECIALIDAD(
    ESPECIALIDAD_ID    NUMBER(5, 0)     NOT NULL,
    NOMBRE             VARCHAR2(100)    NOT NULL,
    ANIOS              NUMBER(1, 0)     NOT NULL,
    REQUISITO          VARCHAR2(40)     NOT NULL,
    CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY (ESPECIALIDAD_ID)
)
;



-- 
-- TABLE: MEDICO 
--

CREATE TABLE MEDICO(
    MEDICO_ID          NUMBER(10, 0)     NOT NULL,
    NOMBRE             VARCHAR2(40)      NOT NULL,
    AP_PATERNO         VARCHAR2(40)      NOT NULL,
    AP_MATERNO         VARCHAR2(40)      NOT NULL,
    CEDULA             VARCHAR2(18)      NOT NULL,
    TRAYECTORIA        VARCHAR2(4000)    NOT NULL,
    ESPECIALIDAD_ID    NUMBER(5, 0)      NOT NULL,
    CONSTRAINT MEDICO_PK PRIMARY KEY (MEDICO_ID), 
    CONSTRAINT MEDICO_ESPECIALIDAD_FK FOREIGN KEY (ESPECIALIDAD_ID)
    REFERENCES ESPECIALIDAD(ESPECIALIDAD_ID)
)
;



-- 
-- TABLE: PACIENTE 
--

CREATE TABLE PACIENTE(
    PACIENTE_ID              NUMBER(10, 0)     NOT NULL,
    NOMBRE                   VARCHAR2(40)      NOT NULL,
    AP_PATERNO               VARCHAR2(40)      NOT NULL,
    AP_MATERNO               VARCHAR2(40)      NOT NULL,
    GENERO                   VARCHAR2(40)      NOT NULL,
    NUM_SEGURO               VARCHAR2(13)      NOT NULL,
    CURP                     VARCHAR2(18)      NOT NULL,
    DIRECCION                VARCHAR2(1000)    NOT NULL,
    EMAIL                    VARCHAR2(200),
    FECHA_INICIO_VIGENCIA    DATE              NOT NULL,
    FECHA_FIN_VIGENCIA       VARCHAR2(40),
    OCUPACION                VARCHAR2(100),
    ANTECEDENTES             VARCHAR2(2000),
    CONSTRAINT PACIENTE_PK PRIMARY KEY (PACIENTE_ID)
)
;



-- 
-- TABLE: CITA 
--

CREATE TABLE CITA(
    CITA_ID           NUMBER(10, 0)    NOT NULL,
    FECHA_CITA        TIMESTAMP(6)     NOT NULL,
    CONSULTORIO       VARCHAR2(5)      NOT NULL,
    PACIENTE_ID       NUMBER(10, 0)    NOT NULL,
    DIAGNOSTICO_ID    NUMBER(10, 0)    NOT NULL,
    MEDICO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CITA_PK PRIMARY KEY (CITA_ID), 
    CONSTRAINT CITA_DIAGNOSTICO_FK FOREIGN KEY (DIAGNOSTICO_ID)
    REFERENCES DIAGNOSTICO(DIAGNOSTICO_ID),
    CONSTRAINT CITA_MEDICO_FK FOREIGN KEY (MEDICO_ID)
    REFERENCES MEDICO(MEDICO_ID),
    CONSTRAINT CITA_PACIENTE_FK FOREIGN KEY (PACIENTE_ID)
    REFERENCES PACIENTE(PACIENTE_ID)
)
;



-- 
-- TABLE: MEDICAMENTO 
--

CREATE TABLE MEDICAMENTO(
    MEDICAMENTO_ID           NUMBER(10, 0)     NOT NULL,
    NUM_GRUPO_TERAPEUTICO    NUMBER(5, 0)      NOT NULL,
    GRUPO_TERAPEUTICO        VARCHAR2(500)     NOT NULL,
    CLAVE_CBCM               VARCHAR2(1000)    NOT NULL,
    SUBCLAVE                 VARCHAR2(2000)    NOT NULL,
    NOMBRE_GENERICO          VARCHAR2(500)     NOT NULL,
    FORMA_FARMACEUTICA       VARCHAR2(500)     NOT NULL,
    CONCENTRACION            VARCHAR2(2000)    NOT NULL,
    PRESENTACION             VARCHAR2(500)     NOT NULL,
    PRINCIPAL_INDICACION     VARCHAR2(1000),
    INDICACION_SECUNDARIA    VARCHAR2(1000),
    CONTRAINDICACIONES       VARCHAR2(4000),
    UNIDADES_ENVASE          VARCHAR2(1000)    NOT NULL,
    DOSIS_DIARIA             VARCHAR2(1000),
    NOMBRE_GENERAL           VARCHAR2(1000)    NOT NULL,
    CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (MEDICAMENTO_ID)
)
;



-- 
-- TABLE: RECETA 
--

CREATE TABLE RECETA(
    RECETA_ID         NUMBER(10, 0)    NOT NULL,
    CANTIDAD          NUMBER(4, 0)     NOT NULL,
    DIAS              NUMBER(3, 0)     NOT NULL,
    CITA_ID           NUMBER(10, 0)    NOT NULL,
    MEDICAMENTO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT RECETA_PK PRIMARY KEY (RECETA_ID), 
    CONSTRAINT RECETA_CITA_FK FOREIGN KEY (CITA_ID)
    REFERENCES CITA(CITA_ID),
    CONSTRAINT RECETA_MEDICAMENTO_FK FOREIGN KEY (MEDICAMENTO_ID)
    REFERENCES MEDICAMENTO(MEDICAMENTO_ID)
)
;







