insert into especialidad(especialidad_id,nombre,anios,requisito) values(1,'Anatomia Patologica',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(2,'Anestesiologia y Recuperacion',3,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(3,'Anestesiologia Pediatrica',1,'Especialista en Anestesiologia');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(4,'Cardiologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(5,'Cardiologia Pediatrica',2,'Especialista en Pediatria');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(6,'Cirugia General',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(7,'Cirugia Pediatrica',5,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(8,'Cirugia Plastica y Reconstructiva',2,'tercer  de Cirugia General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(9,'Cirugia Toracica General',5,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(10,'Cirugia Cardiovascular Toracica',5,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(11,'Dermatologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(12,'Endocrinologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(13,'Gastroenterologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(14,'Geriatria y Gerontologia',5,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(15,'Ginecologia y Obstetricia',3,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(16,'Ginecologia Oncologica',2,'Ginecologia y Obstetricia');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(17,'Hematologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(18,'Hematologia Pediatrica',2,'Pediatria');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(19,'Infectologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(20,'Infectologia Pediatrica',2,'Pediatria');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(21,'Inmunologia Clinica Medica',2,'Medicina Interna o Pediatria');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(22,'Medicina Critica Pediatrica',2,'Pediatria');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(23,'Medicina Critica y Terapia Intensiva',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(24,'Medicina de Emergencias',3,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(25,'Medicina Interna',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(26,'Medicina Familiar y Comunitaria',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(27,'Medicina Fisica y Rehabilitacion',3,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(28,'Medicina Materno Fetal',3,'Ginecologia y Obstetricia');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(29,'Medicina Paliativa',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(30,'Nefrologia',2,'Medicina Interna');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(31,'Nefrologia Pediatrica',2,'Pediatria');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(32,'Neonatologia',2,'Pediatria');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(33,'Neumologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(34,'Neumologia Pediatrica',2,'Pediatria');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(35,'Neurocirugia',6,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(36,'Neurologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(37,'Oftalmologia',3,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(38,'Oftalmologia Pediatrica',1.5,'Oftalmologia');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(39,'Oncologia Medica',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(40,'Oncologia Quirurgica',2,'Cirugia General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(41,'Ortopedia y Traumatologia',5,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(42,'Ortopedia y Traumatologia',2,'Ortopedia y Traumatologia');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(43,'Otorrinolaringologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(44,'Patologia Pediatrica',2,'Anatomia Patologica');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(45,'Pediatria',3,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(46,'Psicologia Clinica',2,'Licenciatura en Psicologia');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(47,'Psiquiatria',3,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(48,'Radiologia e Imagenes Medicas',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(49,'Radioterapia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(50,'Reumatologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(51,'Urologia',4,'Medicina General');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(52,'Urologia Pediatrica',2,'Urologia');
insert into especialidad(especialidad_id,nombre,anios,requisito) values(53,'Vascular Periferico',4,'Medicina General');
